# Generated by Django 3.0.3 on 2020-02-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 10, 25, 24, 186812))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('progress', models.CharField(max_length=30)),
            ],
        ),
    ]
