# Generated by Django 3.0.3 on 2020-02-22 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 11, 35, 919839), null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 11, 35, 919757)),
        ),
    ]
