# Generated by Django 3.0.3 on 2020-02-22 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200222_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 20, 1, 497279, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 20, 1, 497206, tzinfo=utc)),
        ),
    ]
