# Generated by Django 3.0.3 on 2020-02-22 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200222_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 48, 10, 998711, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 18, 48, 10, 998650, tzinfo=utc)),
        ),
    ]
