# Generated by Django 3.0.3 on 2020-02-22 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200222_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 19, 38, 55, 666609, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 19, 38, 55, 666540, tzinfo=utc)),
        ),
    ]
